# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlGpt < Formula
  desc "kubectl-gpt is a kubectl plugin to generate `kubectl` commands from natural language input by using OpenAI's GPT model."
  homepage "https://github.com/devinjeon/kubectl-gpt"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.0.0/kubectl-gpt_v1.0.0_darwin_arm64.tar.gz"
      sha256 "0a62a346f5128b5b89fd0438bdbaea6097febfe8dd1069b2b2f457bc2d157cdc"

      def install
        bin.install "kubectl-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.0.0/kubectl-gpt_v1.0.0_darwin_x86_64.tar.gz"
      sha256 "da542a7ec6a3317a4eb926b42f4ab1aced97c286a1df8d62b696e13740e04f41"

      def install
        bin.install "kubectl-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.0.0/kubectl-gpt_v1.0.0_linux_arm64.tar.gz"
      sha256 "83c56b09980d5c98ac346a7d2c091b647fc0e115710c6053011ee86e0916a7c5"

      def install
        bin.install "kubectl-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.0.0/kubectl-gpt_v1.0.0_linux_x86_64.tar.gz"
      sha256 "dc5e31f655a71d469495b4d69f4c35a76b4c325b41af27c0fd325ead21d23e20"

      def install
        bin.install "kubectl-gpt"
      end
    end
  end
end
