# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlGpt < Formula
  desc "kubectl-gpt is a kubectl plugin to generate `kubectl` commands from natural language input by using OpenAI's GPT model."
  homepage "https://github.com/devinjeon/kubectl-gpt"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.2.0/kubectl-gpt_v1.2.0_darwin_arm64.tar.gz"
      sha256 "0153b76473ba90e9e78a570cc868e39fc4f8546e3954d1fa1983d47bd2c484b0"

      def install
        bin.install "kubectl-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.2.0/kubectl-gpt_v1.2.0_darwin_x86_64.tar.gz"
      sha256 "a65858563665f1b421b80cb0ec446197f080deed2cd773f5fa22e5214e8319db"

      def install
        bin.install "kubectl-gpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.2.0/kubectl-gpt_v1.2.0_linux_arm64.tar.gz"
      sha256 "8344ecd860afbc67ce8783b306fc96b0db87f4dca6369850215402c117905523"

      def install
        bin.install "kubectl-gpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devinjeon/kubectl-gpt/releases/download/v1.2.0/kubectl-gpt_v1.2.0_linux_x86_64.tar.gz"
      sha256 "1104ee165477c67b546f3c9918b12198b959e26481957e8623ab56cb807c1ac6"

      def install
        bin.install "kubectl-gpt"
      end
    end
  end
end
